version: "3"

services:
  ahasecret:
    build: .
    volumes:
      - ahadb:/usr/src/app/db/database
    ports:
      - "9292:9292"
    environment:
      RACK_ENV: production
      # URL: "https://please.change.me.now"
      MEMCACHE: "memcached:11211"
    depends_on:
      - memcached

  memcached:
    image: "memcached:latest"
    ports:
      - "11211:11211"

volumes:
  ahadb:
