---
version: "3"

services:
  ahasecret:
    # build: .
    image: ghcr.io/aha-oida/aha-secret:latest
    volumes:
      - ahadb:/usr/src/app/db/database
      # - ./config.yml:/usr/src/app/config/config.yml
      # - ./custom.css:/usr/src/app/public/stylesheets/custom.css
    ports:
      - "9292:9292"
    #  environment:
       #      RACK_ENV: production
       #      AHA_SECRET_BASE_URL: "https://please.change.me.now"
       #      AHA_SECRET_PERMITTED_ORIGINS: "https://please.change.me.now"
       #      AHA_SECRET_MEMCACHE_URL: "memcached:11211"
       #      AHA_SECRET_SESSION_SECRET: "your-secure-random-session-secret-here"
    env_file: .env
    depends_on:
      - memcached

  memcached:
    image: "memcached:latest"

volumes:
  ahadb:
