---
# activerecord database configuration
development:
  adapter: sqlite3
  database: db/database/development.sqlite3

test:
  adapter: sqlite3
  database: db/database/test.sqlite3

production:
  adapter: sqlite3
  database: db/database/production.sqlite3
