name: Check links in markdown files

on:
  pull_request:
    branches:
      - main
jobs:
  condition_markdown_files:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check_markdown_files.outputs.changed }}
    steps:
      - name: Check if markdown files changed
        id: check_markdown_files
        run: |
          md_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.md$' || true)
          if [ -n "$md_files" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
  check_links:
    runs-on: ubuntu-latest
    needs: condition_markdown_files
    if: needs.condition_markdown_files.outputs.changed != 'false'
    steps:
    - uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.7' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        cache-version: 0 # Increment this number if you need to re-download cached gems
    - name: Checks
      run: |
        gem install awesome_bot -v '1.20.0'
        awesome_bot *.md --allow-ssl -a 302,429 --allow-dupe --skip-save-results --white-list www.gnu.org